### ISSUE TITLE
why PARE don't have fitting part?

### ISSUE THREAD

**Issue by jinfagang** [mkocabas/PARE#16]
From VIBE, there are some operation when do smpl, it will do fitting in a train loop, but PARE seems don't have it.
Why it was still performance better than VIBE?

**Comment by mkocabas** [comment]
Hi @jinfagang,

I have added the SMPLify fitting feature with commit https://github.com/mkocabas/PARE/commit/e997cc458d1a3e5fe222174fb59c055c2b8f8ac4. You can give it a try. It is implemented for image folder input for now.
