### ISSUE TITLE
Any improvement for multiview SMPL fitting?

### ISSUE THREAD

**Issue by Charlulote** [mkocabas/PARE#17]
I'm trying to fit SMPL to scans. Currently, I just render it in different views and choose the result predicted by PARE with lowest Chamfer distance. Is there any feasible improvement on view consistency?

**Comment by mkocabas** [comment]
Hi @Charlulote,

Our goal in PARE is single-view HPS estimation. You can try another toolbox like EasyMocap (https://github.com/zju3dv/EasyMocap) to do multi-view SMPL fitting.
