### ISSUE TITLE
size not very fit??

### ISSUE THREAD

**Issue by jinfagang** [mkocabas/PARE#18]
![image](https://user-images.githubusercontent.com/21303438/159945038-df58f843-eecc-41bf-af6a-f0f56a5615df.png)

for far , it looks normal, but if near:

![image](https://user-images.githubusercontent.com/21303438/159945850-4dbb54b8-af28-49fc-a844-c51283387aeb.png)

the predict mesh bigger than real on image.

**Comment by jjhooon** [comment]
Is this the result of training model without training instruction?
If so, Could you tell me how to train the model?
