### ISSUE TITLE
pare-github-data

### ISSUE THREAD

**Issue by cytcyt1111** [mkocabas/PARE#20]
Hi

I`m tring to run demo, but the file pare-github-data.zip on https://www.dropbox.com/s/aeulffqzb3zmh8x/pare-github-data.zip cannot download.
Is there any other way can i get it?

thank u so much

**Comment by winshot-thu** [comment]
You can download it from Chrome and push it to your GPU server.

**Comment by cytcyt1111** [comment]
您好，已收到您的邮件，请放心。

**Comment by mkocabas** [comment]
Hi @cytcyt1111,

I can download it without any problem using different browsers and accounts. You can check whether you have access to dropbox. If not, you might try using VPN.

**Comment by junziAFAN** [comment]
> Hi
> 
> I`m tring to run demo, but the file pare-github-data.zip on https://www.dropbox.com/s/aeulffqzb3zmh8x/pare-github-data.zip cannot download. Is there any other way can i get it?
> 
> thank u so much

通用场景
Can you download it now? Could you send me a copy? Thank you. My email address is:3221283525.Thank you for your trouble. Your help means a lot to me.

**Comment by cytcyt1111** [comment]
您好，已收到您的邮件，请放心。
