### ISSUE TITLE
Could you provide the 3DPW-OCC dataset?

### ISSUE THREAD

**Issue by hygenie1228** [mkocabas/PARE#21]
Thanks for the exciting work.

Can you provide the 3DPW-OCC dataset mentioned in the paper?

It would be appreciated if you provide a 3DPW-OCC annotation file or video sequence names.

Thank you.

**Comment by mkocabas** [comment]
Hi @hygenie1228,

It is provided here: https://github.com/mkocabas/PARE/blob/master/pare/core/constants.py#L132.

**Comment by yangyang32111** [comment]
@hygenie1228 Hi,have you got the 3DPW-OCC dataset yet?If you have the dataset, could you mind  share it to me?Thank you very much! And my email is 1006220921@qq.com.

**Comment by hygenie1228** [comment]
Hi @yangyang32111, I followed the above answer by sampling corresponding sequences of 3DPW dataset.
I also get the annotations for evaluation from the 3DPW dataset.
If you follow the answers above, you can compose the dataset easily.
