### ISSUE TITLE
cannot run on windows

### ISSUE THREAD

**Issue by sunmengnan** [mkocabas/PARE#5]
I think it may due to the egl reason.

**Comment by RGH55** [comment]
Since windows is not headless, you don't need to use egl.
So you can just comment that line in `data/demo.py`, `pare/utils/renderer.py`, and `pare/utils/vibe_renderer.py`.
p.s. you need to change all of `subprocess.call(command)` to `subprocess.call(command, shell=True)` in Windows environment.
