### ISSUE TITLE
How to get the Body Part Segmentation labels?

### ISSUE THREAD

**Issue by zhLawliet** [mkocabas/PARE#9]
![image](https://user-images.githubusercontent.com/17424385/144222533-f7f2d530-a319-46e4-bae4-4ae630fd49a7.png)

**Comment by mkocabas** [comment]
You can have a look at this gist: https://gist.github.com/mkocabas/238faa8a24c44d60fb30ffce367f9ec7

**Comment by zhLawliet** [comment]
thanks

**Comment by zhLawliet** [comment]
@mkocabas  thanks, i can get the figure A by the visualize_body_part_segmentation and  the figure B by your PARE，there is a question that how can i correspond the A to B.
figure A
![image](https://user-images.githubusercontent.com/17424385/144231116-50a32577-9d8b-460b-8303-179f5c48549f.png)

figure B
![00000](https://user-images.githubusercontent.com/17424385/144231074-8e4f1465-d8a1-40a1-9f0d-56a90d8aa497.jpg)

**Comment by dqj5182** [comment]
Same question
